# Generated by Django 4.1.7 on 2023-03-14 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('prizes', models.IntegerField()),
                ('dob', models.DateField()),
                ('cnp', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredientName', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('runningLow', models.BooleanField()),
                ('expirationDate', models.DateField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='chefCreator',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.chef'),
            preserve_default=False,
        ),
    ]
