# Generated by Django 4.1.7 on 2023-03-19 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chef_ingredient_food_chefcreator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='chefCreator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='api.chef'),
        ),
        migrations.CreateModel(
            name='ReceipeIndications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantityOfIngredient', models.IntegerField()),
                ('specifications', models.CharField(max_length=1000)),
                ('foodId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.food')),
                ('ingredientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ingredient')),
            ],
        ),
    ]
