# Generated by Django 4.1.7 on 2023-03-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_chef_cnp_alter_chef_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='ingredients',
            field=models.ManyToManyField(to='api.ingredient'),
        ),
    ]
