# Generated by Django 4.1.7 on 2023-04-04 20:36

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_food_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='ingredients',
            field=models.ManyToManyField(through='api.ReceipeIndications', to='api.ingredient'),
        ),
        migrations.AlterField(
            model_name='chef',
            name='firstName',
            field=models.CharField(max_length=100, validators=[api.models.Chef.validateNames]),
        ),
        migrations.AlterField(
            model_name='chef',
            name='lastName',
            field=models.CharField(max_length=100, validators=[api.models.Chef.validateNames]),
        ),
        migrations.AlterField(
            model_name='food',
            name='expirationDate',
            field=models.DateField(validators=[api.models.Food.validateDates]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.IntegerField(validators=[api.models.Ingredient.validateQuantity]),
        ),
    ]
