# Generated by Django 4.1.7 on 2023-04-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_food_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='expirationDate',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='expirationDate',
            field=models.CharField(max_length=20),
        ),
    ]
