# Generated by Django 4.1.7 on 2023-03-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodName', models.CharField(max_length=100)),
                ('proteinGrams', models.IntegerField()),
                ('sugarGrams', models.IntegerField()),
                ('expirationDate', models.DateField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
