# Generated by Django 4.1.7 on 2023-03-22 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_food_chefcreator_receipeindications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='cnp',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='chef',
            name='dob',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='expirationDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='receipeindications',
            name='foodId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='api.food'),
        ),
        migrations.AlterField(
            model_name='receipeindications',
            name='ingredientId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='api.ingredient'),
        ),
    ]
