# Generated by Django 4.1.7 on 2023-03-22 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_food_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='ingredients',
        ),
    ]
