# Generated by Django 4.1.7 on 2023-04-05 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_food_ingredients_alter_chef_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='ingredients',
        ),
        migrations.AlterField(
            model_name='receipeindications',
            name='foodId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='api.food'),
        ),
        migrations.AlterField(
            model_name='receipeindications',
            name='ingredientId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='api.ingredient'),
        ),
    ]
